-- Her ilin haftanýn en çok hangi gününde 
-- satýþ yaptýðýný öðrenip ona göre þehir ve
-- günlere özel kampanya yapmak istiyoruz.
-- Þehirlerin haftanýn günlerine göre ne kadarlýk satýþ yaptýðý
-- bilgisini sql kodu ile yazýnýz.

SELECT DISTINCT CITY,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '01.PZT') AS PAZARTESI,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '02.SAL') AS SALI,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '03.ÇAR') AS CARSAMBA,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '04.PER') AS PERSEMBE,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '05.CUM') AS CUMA,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '06.CMT') AS CUMARTESI,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '07.PAZ') AS PAZAR
FROM SALEORDERS S
ORDER BY 1

