-- MÜÞTERÝLERÝMÝZÝN SÝSTEMDE KAYITLI ADRES
-- SAYISINI VE SON ALIÞVERÝÞ YAPTIÐI ADRES BÝLGÝSÝNÝ
-- ÞEHÝR, ÝLÇE VE SEMTÝ ÝLE BÝRLÝKTE ÞEKÝLDEKÝ GÝBÝ
-- GETÝREN SORGUYU YAZINIZ

SELECT TMP.NAMESURNAME,TMP.ADDRESSCOUNT,A.ADDRESSTEXT,C.CITY,T.TOWN,D.DISTRICT FROM (
	SELECT U.ID, U.NAMESURNAME,
		(SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID) AS ADDRESSCOUNT,
			(
			SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID = U.ID ORDER BY DATE_ DESC
			)
	 LASTADDRESSID
FROM USERS U ) TMP
INNER JOIN ADDRESS A
ON A.ID = TMP.LASTADDRESSID
INNER JOIN CITIES C
ON C.ID = A.CITYID
INNER JOIN TOWNS T
ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D
ON D.ID = A.DISTRICTID