-- HER KATEGORÝNÝN ÝÇERÝSÝNDE EN ÇOK SATAN
-- MARKAYI ÞEKÝLDEKÝ GÝBÝ GETÝREN SORGUYU YAZINIZ

SELECT ITM.CATEGORY1,ITM.BRAND,SUM(OD.LINETOTAL) AS TOTALPRICE FROM ORDERDETAILS OD
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY ITM.CATEGORY1,ITM.BRAND
ORDER BY ITM.CATEGORY1,SUM(OD.LINETOTAL)