-- MÜÞTERÝLERÝN SÝSTEMDE KAYITLI ADRES SAYISINI VE 
-- SON ALIÞVERÝÞ YAPTIÐI ADRES BÝLGÝSÝNÝ ÞEKÝLDEKÝ
-- GÝBÝ GETÝREN SORGUYU YAZINIZ

SELECT U.ID, U.NAMESURNAME,
	(SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID) AS ADDRESSCOUNT,
		(
		SELECT ADDRESSTEXT FROM ADDRESS WHERE ID IN (SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID = U.ID ORDER BY DATE_ DESC)
		)
FROM USERS U
