-- OCAK AYI ÝÇERÝSÝNDE EN AZ 10 GÜN BOYUNCA
-- GÜNLÜK 500 TL VE ALTINDA SÝPARÝÞ VEREN ÞEHÝRLERÝ 
-- ÞEKÝLDEKÝ GÝBÝ LÝSTELETTÝREN SORGUYU YAZINIZ.

SELECT CITY,COUNT(*) FROM (
SELECT 
C.CITY,CONVERT(DATE,O.DATE_) AS DATE_, SUM(O.TOTALPRICE) AS TOTALPRICE
 FROM ORDERS O
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID = A.CITYID
WHERE O.DATE_ BETWEEN '20190101' AND '2019-01-31 23:59:59'
--AND C.CITY = 'BURSA'
GROUP BY C.CITY, CONVERT(DATE,O.DATE_)
HAVING SUM(O.TOTALPRICE) < 500) TMP
GROUP BY CITY
HAVING COUNT(CITY)>=10
