-- HER MARKANIN ANA KATEGORÝYE GÖRE 
-- EN ÇOK SATAN CATEGORY1 ALANINI ÞEKÝLDEKÝ
-- GÝBÝ GETÝREN SORGUYU YAZINIZ

SELECT ITM.BRAND,ITM.CATEGORY1, SUM(OD.LINETOTAL) AS TOTALPRICE FROM 
ORDERDETAILS OD
INNER JOIN ITEMS ITM 
ON ITM.ID = OD.ITEMID
GROUP BY ITM.BRAND,ITM.CATEGORY1
ORDER BY ITM.BRAND, TOTALPRICE DESC