-- SALESORDER TABLOSU ÞEHÝRLERE GÖRE HANGÝ
-- AYDA NE KADARLIK SATIÞ YAPILDIÐI BÝLGÝSÝNÝ
-- ÇEKEN SQL SORGUSUNU YAZINIZ.

SELECT CITY,MONTH_,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS
GROUP BY CITY,MONTH_
ORDER BY CITY,MONTH_