-- HER BÝR ÜRÜN ZAMAN ÝÇÝNDE FARKLI FÝYATLAR ÝLE SATILMAKTADIR.
-- HER ÜRÜNÜN MÝNÝMUM, MAKSÝMUM VE ORTALAMA NE KADAR FÝYATTAN
-- SATILDIÐI BÝLGÝSÝ ÝLE KAÇ KEZ VE KAÇ ADET SATILDIÐI BÝLGÝSÝNÝ
-- ÞEKÝLDEKÝ GÝBÝ GETÝREN SORGUYU YAZINIZ.

SELECT ITM.BRAND,ITM.CATEGORY1,ITM.ITEMCODE,ITM.ITEMNAME, 
COUNT(OD.ID) AS SALECOUNT,SUM(OD.AMOUNT) AS TOTALAMOUNT, MIN(OD.UNITPRICE) AS MINPRICE , MAX(OD.UNITPRICE) AS MAXPRICE, AVG(OD.UNITPRICE) AS AVGPRICE
FROM ITEMS ITM
INNER JOIN ORDERDETAILS OD ON OD.ITEMID = ITM.ID
GROUP BY ITM.BRAND,ITM.CATEGORY1,ITM.ITEMCODE,ITM.ITEMNAME