-- HANGÝ ÞEHÝRDE KAÇ ERKEK, KAÇ KADIN
-- MÜÞTERÝMÝZÝN OLDUÐU BÝLGÝSÝNÝ ÞEKÝLDEKÝ
-- GÝBÝ GETÝREN SORGUYU YAZINIZ.

SELECT CT.CITY,C.GENDER,COUNT(C.ID) AS CUSTOMERCOUNT 
FROM CUSTOMERS C
INNER JOIN CITIES CT 
ON CT.ID = C.CITYID
GROUP BY CT.CITY, C.GENDER
ORDER BY CT.CITY, C.GENDER
