

-- ÝSTANBULDA KAÇ MÜÞTERÝNÝN OLDUÐUNU
-- GÖSTEREN SORGUYU YAZIN

SELECT CT.CITY, COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C 
INNER JOIN CITIES CT ON CT.ID = C.CITYID
WHERE CT.CITY = 'ÝSTANBUL'
GROUP BY CT.CITY

-- HANGÝ ÞEHÝRDE KAÇ MÜÞTERÝNÝN OLDUÐUNU
-- GÖSTEREN SORGUYU YAZIN

SELECT *, (SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=CT.ID) AS CUSTOMERCOUNT FROM CITIES CT