-- CUSTOMERS TABLOSUNA EKLEDÝÐÝNÝZ AGEGROUP ALANINI
-- 20-35 YAÞ ARASI, 35-45 YAÞ ARASI, 46,55 YAÞ ARASI
-- 55-65 YAÞ ARASI VE 65 YAÞ ÜSTÜ OLARAK GÜNCELLEYÝN


UPDATE CUSTOMERS SET AGEGROUP = '20-35 YAÞ' WHERE DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35
UPDATE CUSTOMERS SET AGEGROUP = '36-45 YAÞ' WHERE DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45
UPDATE CUSTOMERS SET AGEGROUP = '46-55 YAÞ' WHERE DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55
UPDATE CUSTOMERS SET AGEGROUP = '56-65 YAÞ' WHERE DATEDIFF (YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65
UPDATE CUSTOMERS SET AGEGROUP = '65 YAÞ ÜSTÜ' WHERE DATEDIFF (YEAR,BIRTHDATE,GETDATE()) > 65