-- ÝSTANBULDA YAÞAYIP ÝLÇESÝ
-- BEYKOZ DIÞINDA OLAN MÜÞTERÝLERÝ LÝSTELEYÝNÝZ

SELECT * FROM CUSTOMERS C 
INNER JOIN CITIES CT ON CT.ID = C.CITYID
INNER JOIN DISTRICTS D ON D.ID = C.DISTRICTID
WHERE CT.CITY = 'ÝSTANBUL' AND D.DISTRICT NOT IN ('BEYKOZ')
