-- CUSTOMERS TABLOSUNA YAÞ GRUBU ÝÇÝN
-- YENÝ BÝR ALAN EKLEYÝNÝZ. BU ÝÞLEMÝ
-- HEM MANAGEMENT STDUÝO ÝLE HEM DE SQL KODU
-- ÝLE YAPINIZ ALAN ADI AGEGROUP VERÝTÝTÝP VARCHAR(50)

ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(50)

