-- HANGÝ ÞEHÝRDE KAÇ ERKEK, KAÇ KADIN
-- MÜÞTERÝMÝZÝN OLDUÐU BÝLGÝSÝNÝ ÞEKÝLDEKÝ
-- GÝBÝ GETÝREN SORGUYU YAZINIZ

SELECT CITY AS SEHIRADI, 
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID = C.ID) AS MUSTERISAYISI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID = C.ID AND GENDER ='E') AS ERKEKSAYÝSÝ,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID = C.ID AND GENDER ='K') AS KADÝNSAYÝSÝ
FROM CITIES C