-- MÜÞTERÝLERÝMÝZÝN TELEFON NUMARALARININ
-- OPERATÖR BÝLGÝSÝNÝ GETÝRMEK ÝSTÝYORUZ.
-- TELNR1 VE TELNR2 ALANLARININ YANINA OPERATOR
-- NUMARASINI (532),(505) GÝBÝ GETÝRMEK ÝSTÝYORUZ.
-- BU SORGU ÝÇÝN GEREKEN SQL CÜMLESÝNÝ YAZINIZ.

SELECT *,
SUBSTRING(TELNR1,1,5) AS OPERATOR1,
SUBSTRING(TELNR2,1,5) AS OPERATOR2
FROM CUSTOMERS
