-- CUSTOMERS TABLOSUNDA MÜÞTERÝNÝN YAÞINA GÖRE HESAPLAYARAK ÞEKÝLDEKÝ 
-- GÝBÝ BÝR SONUÇ GETÝRÝNÝZ. NOT: AGEGROUP ALANI KULLANILMADAN 
-- SORGU GETÝRÝLECEKTÝR

--SELECT
--CASE 
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65 THEN '65 YAÞ ÜSTÜ'
--END AGEGROUP,COUNT(*) AS CUSTOMERCOUNT
--FROM CUSTOMERS
--GROUP BY 
--CASE 
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAÞ ARASI'
--	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65 THEN '65 YAÞ ÜSTÜ'
--END 
--ORDER BY AGEGROUP

SELECT AGEGROUP2,COUNT(TMP.ID) AS CUSTOMERCOUNT FROM 
(
SELECT *,
CASE 
	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ ARASI'
	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ ARASI'
	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ ARASI'
	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAÞ ARASI'
	WHEN  DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 65 THEN '65 YAÞ ÜSTÜ'
END AGEGROUP2
FROM CUSTOMERS
) TMP
GROUP BY AGEGROUP2
ORDER BY AGEGROUP2