-- 10' DAN FAZLA MÜÞTERÝMÝZ OLAN ÞEHÝRLERÝ 
-- MÜÞTERÝ SAYISI ÝLE BÝRLÝKTE MÜÞTERÝ SAYISINA
-- GÖRE FAZLADAN AZA DOÐRU SIRALI ÞEKÝLDE GETÝRÝNÝZ

SELECT CT.CITY,COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C 
INNER JOIN CITIES CT ON CT.ID = C.CITYID
GROUP BY CT.CITY
HAVING COUNT(C.ID) > 10
ORDER BY CUSTOMERCOUNT DESC
