-- CITIES TABLOSUNDAN ANKARA KAYDINI
-- SÝLDÝÐÝMÝZÝ VARSAYALIM. BU DURUMDA
-- ÞEHRÝ ANKARA OLAN MÜÞTERÝLERÝN 
-- ÞEHÝR ALANI BOÞ GELECEKTÝR.
-- ÞEHÝR ALANI BOÞ OLAN MÜÞTERÝLERÝ
-- LÝSTELEYEN SORGUYU YAZINIZ.


DELETE FROM CUSTOMERS WHERE CITYID = 6

SELECT * FROM CUSTOMERS C 
LEFT JOIN CITIES CT ON CT.ID = C.CITYID
WHERE CT.CITY IS  NULL