-- HARRY POTTER , JAMES BOND GÝBÝ
-- SERÝ FÝLMLERÝN KAÇ FÝLMDEN OLUÞTUÐUNU
-- TOPLAMDA NE KADAR BÜTÇE ÝLE ÇEKÝLDÝÐÝNÝ
-- VE NE KADAR HASILAT YAPTIÐINI ÞEKÝLDEKÝ GÝBÝ
-- ÇEKEN SORGUYU YAZINIZ


SELECT C.NAME_ SERÝADI, COUNT(M.FILMID) AS FILM_SAYISI,
SUM(M.BUDGET) AS TOPLAM_BUTCE,ROUND(AVG(M.BUDGET),0) AS ORTALAMA_BUTCE,
SUM(M.REVENUE) AS TOPLAM_HASILAT,AVG(M.REVENUE) AS ORTALAMA_HASÝLAT
FROM COLLECTION_ C
INNER JOIN MOVIE M ON C.COLLECTIONID = M.COLLECTIONID
WHERE C.NAME_ LIKE 'JAMES BOND%'
GROUP BY C.NAME_