-- HANGÝ ÜLKENÝN NE KADAR FÝLM ÜRETTÝÐÝ
-- BÝLGÝSÝNÝ ÞEKÝLDEKÝ GÝBÝ ÇEKEN
-- SORGUYU YAZÝNÝZ

SELECT MC.COUNTRYCODE AS ULKEKODU, C.COUNTRY AS ULKEADI,COUNT(M.FILMID) AS FÝLM_SAYÝSÝ 
FROM MOVIE_COUNTRY MC
INNER JOIN MOVIE M ON M.FILMID = MC.FILMID
INNER JOIN COUNTRY C ON C.CODE = MC.COUNTRYCODE
GROUP BY MC.COUNTRYCODE,C.COUNTRY
ORDER BY 3 DESC