-- HARRY POTTER, JAMES BOND GÝBÝ SERÝ
-- FÝLMLERÝN EN ÇOK BÜTÇELÝ, EN AZ BÜTÇELÝ,
-- FÝLMLERÝNÝ ÞEKÝLDEKÝ GÝBÝ GETÝREN SORGUYU YAZINIZ

SELECT
C.NAME_ AS SERÝ_ADI,
(SELECT COUNT(*) FROM MOVIE WHERE COLLECTIONID = C.COLLECTIONID) AS FILM_SAYISI,
(SELECT SUM(BUDGET) FROM MOVIE WHERE COLLECTIONID = C.COLLECTIONID) AS TOPLAM_BUTCE,
(SELECT SUM(REVENUE) FROM MOVIE WHERE COLLECTIONID = C.COLLECTIONID) AS TOPLAM_HASILAT,
(SELECT TOP 1 STR(YEAR(RELEASE_DATE))+'-'+ TITLE FROM MOVIE WHERE COLLECTIONID = C.COLLECTIONID ORDER BY BUDGET DESC) AS ENCOK_BUTCELI_FILM
FROM COLLECTION_ C
ORDER BY 2 DESC