-- AMERÝKALI VE JAPON ÞÝRKETLERÝN
-- BÝRLÝKTE YAPIMCILIÐINI YAPTIÐI
-- FÝLMLERÝ ÞEKÝLDEKÝ GÝBÝ LÝSTELEYEN SORGUYU YAZINIZ

SELECT M.FILMID, MC.COUNTRYCODE AS ULKEKODU, C.COUNTRY AS ULKEADI,M.TITLE,M.ORIGINAL_TITLE AS FÝLM_SAYÝSÝ 
FROM MOVIE_COUNTRY MC
INNER JOIN MOVIE M ON M.FILMID = MC.FILMID
INNER JOIN COUNTRY C ON C.CODE = MC.COUNTRYCODE
WHERE C.CODE = 'US'
AND M.FILMID IN (SELECT FILMID FROM MOVIE_COUNTRY WHERE COUNTRYCODE ='JP')

