-- Ýstediðiniz bir kiþinin TMDB sayfasýndaki bilgileri getiriniz.

SELECT NAME_,BIRTHDAY,

(DATEDIFF(DAY,BIRTHDAY,GETDATE())/365) AGER,BIOGRAPHY,
ALSO_KNOWN_AS,
CASE
	WHEN GENDER = 2 THEN 'MALE'
	WHEN GENDER = 1 THEN 'FEMALE'
END AS GENDER,

PLACE_OF_BIRTH,COUNTRY,

(SELECT COUNT(*) FROM CAST_CREDIT WHERE PERSONID=P.PERSONID) AS CASTCREDITCOUNT,
(SELECT COUNT(*) FROM CREW_CREDIT WHERE PERSONID=P.PERSONID) AS CASTCREDITCOUNT,
*
FROM PERSON P WHERE NAME_ LIKE 'Denzel Washington'