-- iSTANBULDA WOLKSWAGEN PASSAT MARKA BÝR ARAÇ ARIYORUZ
-- KRÝTERLERÝMÝZ ÞU ÞEKÝLDE
-- KÝMDEN: SAHÝBÝNDEN
-- MODEL:2014-2018 ARASI
-- VÝTES:OTOMATÝK
--YAKIT:DÝZEL
--SIRALAMA:KÝLOMETRE VE FÝYATA GÖRE

SELECT U.NAMESURNAME,C.CITY,T.TOWN,D.DISTRICT,O.TITLE, O.BRAND,O.MODEL,O.PRICE,O.YEAR_,O.KM,O.FUEL,O.SHIFTTYPE,O.COLOR,O.VARYANT
FROM WEBOFFERS O
INNER JOIN CITY C ON C.ID=O.CITYID
INNER JOIN TOWN T ON T.ID = O.TOWNID
INNER JOIN DISTRICT D ON D.ID = O.DISTRICTID
INNER JOIN USER_ U ON U.ID = O.USERID
WHERE C.CITY = 'ÝSTANBUL'
AND O.SHIFTTYPE IN ('Yarý Otomatik Vites','Otomatik Vites')
AND O.BRAND = 'Volkswagen' AND O.MODEL = 'Passat'
AND O.FUEL = 'Dizel' AND O.FROMWHO = 'Sahibinden'
AND O.YEAR_ BETWEEN 2014 AND 2018
ORDER BY KM,PRICE