-- BMW MARKA ARAÇLARI ANKARA,ÝSTANBUL VE ÝZMÝRDE 
-- LÝSTELETTÝREN SORGUYU YAZINIZ.
-- BURADA SORGUYA GÖNDERÝLEN ÞEHÝR ÝSÝMLERÝ
-- TEKER TEKER DEÐÝL VÝRGÜL ÝLE BÝRLEÞTÝRÝLEREK GÖNDERÝLECEK
-- 'ANKARA,ÝSTANBUL,ÝZMÝR' ÞEKLÝNDE

SELECT U.NAMESURNAME,C.CITY,T.TOWN,D.DISTRICT,O.TITLE, O.BRAND,O.MODEL,O.PRICE,O.YEAR_,O.KM,O.FUEL,O.SHIFTTYPE,O.COLOR,O.VARYANT
FROM WEBOFFERS O
INNER JOIN CITY C ON C.ID=O.CITYID
INNER JOIN TOWN T ON T.ID = O.TOWNID
INNER JOIN DISTRICT D ON D.ID = O.DISTRICTID
INNER JOIN USER_ U ON U.ID = O.USERID
WHERE O.BRAND = 'BMW' AND
C.CITY IN ( SELECT VALUE FROM string_split('ANKARA,ÝSTANBUL,ÝZMÝR',','))
