-- yýllara göre iþe alýnan personel sayýsýný
-- kadýn ve erkek bazýnda listelettiren sorguyu yazýnýz

SELECT DISTINCT YEAR(P.INDATE) AS YEAR_, 
(SELECT COUNT(*) FROM PERSON WHERE GENDER = 'E' AND YEAR(INDATE) =YEAR(P.INDATE)) AS MALE_PERSONCOUNT ,
(SELECT COUNT(*) FROM PERSON WHERE GENDER = 'K' AND YEAR(INDATE) =YEAR(P.INDATE)) AS FEMALE_PERSONCOUNT 
FROM PERSON P
ORDER BY YEAR_
