-- Þirketimizde departman bazlý halen
-- çalýþmaya devam eden kadýn ve erkek
-- sayýlarýýn þekildeki gibi getiren sorguyu yazýnýz

SELECT *, 
( SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND GENDER='E' AND OUTDATE IS NULL) AS MALE_PERSONCOUNT,
( SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND GENDER='K' AND OUTDATE IS NULL) AS FEMALE_PERSONCOUNT
FROM DEPARTMENT D
ORDER BY D.DEPARTMENT
