-- MAAÞ ORTALAMASI 5.500 TL' DEN FAZLA OLAN
-- DEPARTMANLARI LÝSTELEYECEK SORGUYU YAZINIZ

SELECT D.DEPARTMENT, AVG(P.SALARY) AS AVG_SALARY FROM DEPARTMENT D
INNER JOIN PERSON P ON P.DEPARTMENTID=D.ID
GROUP BY D.DEPARTMENT
HAVING AVG(P.SALARY) > 5000
