-- BIR MAGAZANIN GUN BAZLI SATIS RAKAMLARI

SELECT BRANCH AS SUBE,DATE_ AS TARIH,SUM(LINENET) TOPLAMSATÝS,COUNT(BRANCH) AS SATÝRSAYÝSÝ FROM SALES 
WHERE BRANCH = 'BURSA SUBESÝ' --AND DATE_='2017-01-05'
GROUP BY BRANCH,DATE_
ORDER BY DATE_ DESC