select 
BRANCH,
SUM(LINENET) AS TOPLAMSATÝS,
COUNT(*) AS SATÝRSAYÝSÝ,
MIN(LINENET) AS ENDUSUKFIYAT,MAX(LINENET) AS ENYUKSEKFIYAT,
AVG(LINENET) AS ORTALAMASATISFIYATI
from SALES 
GROUP BY BRANCH ORDER BY SUM(LINENET) DESC