-- EN COK SATIS YAPILAN URUN KATEGORILERI

SELECT I.CATEGORY1,SUM(OD.TOTALPRICE) AS TOTAL FROM ITEM I
INNER JOIN ORDERDETAIL OD ON OD.ITEMID = I.ID
GROUP BY I.CATEGORY1
ORDER BY SUM(OD.TOTALPRICE) DESC
