SELECT U.USERNAME_,A.ADDRESSTEXT,C.CITY,T.TOWN,D.DISTRICT
FROM USER_ U
JOIN ADDRES A ON U.ID = A.USERID
JOIN CITY C ON C.ID = A.CITYID
JOIN TOWN T ON T.ID = A.TOWNID
JOIN DISTRICT D ON D.ID = A.DISTRICTID
WHERE U.ID = 1

