-- SUB QUERY ILE MUSTERI BILGISI GETIRME

SELECT ID,NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) AS BASKETCOUNT,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS LASTBASKETDATE
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) > 0