-- EN COK SATIS YAPILAN 10 MUSTERI

SELECT TOP 10 U.USERNAME_,U.NAMESURNAME,SUM(BD.TOTAL) AS TOTAL
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID = B.ID
GROUP BY U.USERNAME_,U.NAMESURNAME 
ORDER BY 3 DESC