-- ASCII
SELECT ASCII ('A') --65
SELECT CHAR(65) --A

-- SUBSTRING 
SELECT SUBSTRING('KALEM',1,3) -- KAL


-- CHARINDEX
SELECT CHARINDEX('A','KALEM',1) --2

-- CONCAT
SELECT CONCAT('KAL','EM') --KALEM
SELECT CONCAT_WS(' ','BERKAY','KULAK') -- BERKAY KULAK

-- FORMAT
SELECT FORMAT(GETDATE(),'d','en-us') -- 5/2/2022

-- LEFT
SELECT LEFT('BERKAY KULAK',4) -- BERK

-- RIGHT
SELECT RIGHT('BERKAY KULAK',4) -- ULAK

-- LEN
SELECT LEN('KALEM') -- 5

-- TRIM
SELECT TRIM('  BERKAY KULAK    ') -- BERKAY KULAK--

-- LOWER
SELECT LOWER('BERKAY') -- berkay

-- UPPER
SELECT UPPER('berkay') -- BERKAY

-- REVERSE
SELECT REVERSE('BERKAY') -- YAKREB

-- REPLICATE
SELECT REPLICATE('0',5) -- 00000

-- REPLACE
SELECT REPLACE('ACILI AYRAN','ACILI','SOGUK') -- SOGUK AYRAN